[package]
authors = ["Parity Technologies <admin@parity.io>"]
name = "cumulus-relay-chain-local"
version = "0.1.0"
edition = "2021"

[dependencies]
polkadot-client = { git = "https://github.com/tauruswei/polkadot", branch = "release-v0.9.16" }
polkadot-service = { git = "https://github.com/tauruswei/polkadot", branch = "release-v0.9.16" }

cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }

sp-core = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-api = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-blockchain = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-consensus = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-state-machine = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }

sc-client-api = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sc-consensus-babe = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sc-network = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sc-service = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sc-telemetry = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sc-tracing = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }

parking_lot = "0.11.1"
tracing = "0.1.25"
async-trait = "0.1.52"
futures = { version = "0.3.1", features = ["compat"] }
futures-timer = "3.0.2"

[dev-dependencies]
# Cumulus deps
cumulus-test-service = { path = "../../test/service" }

# Polkadot deps
polkadot-test-client = { git = "https://github.com/tauruswei/polkadot", branch = "release-v0.9.16" }
polkadot-primitives = { git = "https://github.com/tauruswei/polkadot", branch = "release-v0.9.16" }

# substrate deps
sp-keyring = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
