[package]
name = "shell-runtime"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = ["derive"] }
log = { version = "0.4.14", default-features = false }
parachain-info = { path = "../pallets/parachain-info", default-features = false }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.132", optional = true, features = ["derive"] }

# Substrate dependencies
sp-std = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-api = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-io = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-version = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-core = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-session = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-offchain = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-block-builder = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-transaction-pool = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-inherents = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }

frame-support = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
frame-executive = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
frame-system = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }

# try-runtime stuff.
frame-try-runtime = { git = "https://github.com/tauruswei/substrate", default-features = false, optional = true , branch = "polkadot-v0.9.16" }

# Cumulus dependencies
cumulus-pallet-parachain-system = { path = "../../pallets/parachain-system", default-features = false }
cumulus-primitives-core = { path = "../../primitives/core", default-features = false }
cumulus-primitives-utility = { path = "../../primitives/utility", default-features = false }
cumulus-pallet-dmp-queue = { path = "../../pallets/dmp-queue", default-features = false }
cumulus-pallet-xcm = { path = "../../pallets/xcm", default-features = false }
xcm = { git = "https://github.com/tauruswei/polkadot", default-features = false, branch = "release-v0.9.16" }
xcm-builder = { git = "https://github.com/tauruswei/polkadot", default-features = false, branch = "release-v0.9.16" }
xcm-executor = { git = "https://github.com/tauruswei/polkadot", default-features = false, branch = "release-v0.9.16" }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }

[features]
default = [ "std" ]
std = [
	"codec/std",
	"scale-info/std",
	"serde",
	"log/std",
	"sp-api/std",
	"sp-std/std",
	"sp-io/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"sp-offchain/std",
	"sp-session/std",
	"sp-block-builder/std",
	"sp-transaction-pool/std",
	"sp-inherents/std",
	"frame-support/std",
	"frame-executive/std",
	"frame-system/std",
	"parachain-info/std",
	"cumulus-pallet-parachain-system/std",
	"cumulus-pallet-dmp-queue/std",
	"cumulus-pallet-xcm/std",
	"cumulus-primitives-core/std",
	"cumulus-primitives-utility/std",
	"xcm/std",
	"xcm-builder/std",
	"xcm-executor/std",
]
try-runtime = [
	"frame-try-runtime",
	"frame-executive/try-runtime",
]
