[package]
name = "cumulus-primitives-timestamp"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Provides timestamp related functionality for parachains."

[dependencies]
# Substrate dependencies
sp-timestamp = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-inherents = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }
sp-std = { git = "https://github.com/tauruswei/substrate", default-features = false, branch = "polkadot-v0.9.16" }

# Cumulus dependencies
cumulus-primitives-core = { path = "../core", default-features = false }

[dev-dependencies]
# Substrate dependencies
sp-tracing = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-runtime = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }
sp-consensus = { git = "https://github.com/tauruswei/substrate", branch = "polkadot-v0.9.16" }

# Cumulus dependencies
cumulus-test-client = { path = "../../test/client" }
cumulus-test-relay-sproof-builder = { path = "../../test/relay-sproof-builder" }

# Other deps
codec = { package = "parity-scale-codec", version = "2.3.0", default-features = false, features = [ "derive" ] }
futures = "0.3.5"

[features]
default = [ "std" ]
std = [
	"sp-timestamp/std",
	"sp-inherents/std",
	"sp-std/std",
	"cumulus-primitives-core/std",
]
